# Generated by Django 5.2.9 on 2025-12-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
    ]
