# Generated by Django 5.2.9 on 2025-12-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_tax_amount_remove_invoice_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
