# Generated by Django 5.2.9 on 2025-12-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_change_to_single_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
    ]
